<?php
    $doctype = "<!DOCTYPE html>\n";
    echo $doctype;
    $html = "<html \n";
    $html .= "<head>\n" ;
    $html .= "<title>MOD Scripts con (X)HTML y PHP</title>\n" ;
    $html .= "<meta charset=\"utf-8\"/>\n" ;
    $html .= "<meta name= \"viewport\" content=\"width=device-width,user-scalable=no,initialscale=1.0,maximum-scale=1.0,minimum-scale=1.0\"/>\n" ;
    $html .= " <link rel=\"stylesheet\" media=\"screen\" href=\"css/htmlphp.css\">\n" ;
    $html .= "<Script src=\"js/modernizr.custom.lis.js\"></Script>\n" ;
    $html .= "<script src=\"js/prefixfree.min.js\"></script>\n" ;
    $html .= "</head>\n" ;
    $html .= " <body>\n" ;
    $html .= "<div>\n" ;
    $html .= "<header>\n" ;
    $html .= "<h1>\n" ;
    $html .= "Demostración de HTML y PHP\n" ;
    $html .= "</h1>\n" ;
    $html .= "</header>\n" ;
    $html .= "<section class=\"main\">\n" ;
    $html .= "<article id=\"html\">\n" ;
    $html .= "<div class=\"text\">\n" ;
    $html .= "<p>\n" ;
    $html .= "&lt;!DOCTYPE html&gt; <br/>\n" ;
    $html .= "&lt;html&gt;<br />\n" ;
    $html .= "...\n" ;
    $html .= "</p>\n" ;
    $html .= "<p>\n" ;
    $html .= "Parte de HTML normal\n" ;
    $html .= "</p>\n" ;
    $html .= "<p>\n" ;
    $html .= "&lt;/html&gt;\n" ;
    $html .= "</p>\n" ;
    $html .= "</div>\n" ;
    $html .= "<div class=\"img\">\n" ;
    $html .= "<img src=\"img/html5.png\" alt=\"logo de html5\">\n" ;
    $html .= "</div>\n" ;
    $html .= "</article>\n" ;
    $html .= "<article id=\"php\">\n" ;
    $html .= "<div class=\"text\">\n" ;
    $html .= "<p>&lt;?php<br />\n" ;
    $html .= "...<br />\n" ;
    $html .= "Parte con PHP.</p>\n" ;
    $html .= "<p>?&gt;</p>\n" ;
    $html .= "</div>\n" ;
    $html .= "<div class=\"img\">\n" ;
    $html .= "<img src=\"img/php.png\" alt=\"Logo de HTML5\" />\n" ;
    $html .= "</div>\n" ;
    $html .= "\n</article>\n" ;
    $html .= "</section>\n" ;
    $html .= "<a href=\"..\">Arriba</a>\n" ;
    $html .= "</div>\n" ;
    $html .= "</body>\n" ;
    echo $html;
?>